import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/ThemeContext"; // Adjust the path if necessary

// Components
import Navbar from "@/components/Navbar";
import Profile from "@/components/Profile";

const inter = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anish Tanwar | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ThemeProvider>
          <div className="relative w-full flex items-left justify-center">
            <Navbar />
          </div>
          <div className="w-full max-w-7xl mx-auto relative ">
            <div className="w-1/4 hidden lg:block">
              <Profile />
            </div>
            <div className="absolute right-0  w-full lg:w-3/4 px-4 lg:px-0 top-20 md:top-32 lg:top-0">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
